---
- host: localhost
  name: localhst
  port: 3001
  requests:
    - name: login_success
      resource: /api/auth/login
      method: !post
      body:
        username: nixpig
        password: p4ssw0rd

    - name: login_fail_un
      resource: /api/auth/login
      method: !post
      body:
        username: nonexistent
        password: sd0932jf

    - name: login_fail_pw
      resource: /api/auth/login
      method: !post
      body:
        username: nixpig
        password: sd0932jf

    - name: create_new_user
      resource: /api/user
      method: !post
      auth: !bearer
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA1NTg4MzgsImlzX2FkbWluIjp0cnVlLCJ1c2VyX2lkIjoyfQ.YCms9NhGI7jyNm_53GCgz9gjoRTn8SkGcG-RHQSZor0
      body:
        username: test_user
        email: test@nixpig.dev
        password: p4ssw0rd

    - name: get_users
      resource: /api/user

    - name: get_user_by_id
      resource: /api/user/7

    - name: get_content
      resource: /api/content

    - name: get_content_by_id
      resource: /api/content/24

    - name: create_content
      resource: /api/content
      method: !post
      body:
        title: Some title
        subtitle: Some subtitle in here
        body: Some body content to fill up in here.
        type: post
      auth: !bearer
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA1NTg4MzgsImlzX2FkbWluIjp0cnVlLCJ1c2VyX2lkIjoyfQ.YCms9NhGI7jyNm_53GCgz9gjoRTn8SkGcG-RHQSZor0

    - name: create_content_not_authed
      resource: /api/content
      method: !post
      body:
        title: Not authed post title
        subtitle: This shouldn't work
        body: Some unauthed body content
        type: post

    - name: delete_content_by_id_not_authed
      resource: /api/content/24
      method: !delete

    - name: delete_content_by_id
      resource: /api/content/24
      method: !delete
      auth: !bearer
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA1NTg4MzgsImlzX2FkbWluIjp0cnVlLCJ1c2VyX2lkIjoyfQ.YCms9NhGI7jyNm_53GCgz9gjoRTn8SkGcG-RHQSZor0

    - name: update_content_not_authed
      resource: /api/content/25
      method: !patch
      body:
        id: 14
        title: Some title updated
        subtitle: Updated subtitle
        body: Updated body content in here.
        type: page

    - name: update_content
      resource: /api/content/25
      method: !patch
      body:
        id: 25
        title: Some title updated
        subtitle: Updated subtitle
        body: Updated body content in here.
        type: page
      auth: !bearer
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA1NTg4MzgsImlzX2FkbWluIjp0cnVlLCJ1c2VyX2lkIjoyfQ.YCms9NhGI7jyNm_53GCgz9gjoRTn8SkGcG-RHQSZor0
