version: "3.1"

services:
  web:
    restart: always
    build:
      context: ..
      dockerfile: ./build/package/Dockerfile
    depends_on:
      - db
    env_file: ../.env
    ports:
      - 80:3000
  db:
    restart: always
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example_p4ssW0rd
      - POSTGRES_DB=nixpigweb_
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  db_volume:

networks:
  nixpig_net:
    driver: bridge
