version: "3.1"

services:
  web:
    restart: always
    build:
      context: ..
      dockerfile: ./build/package/Dockerfile
    depends_on:
      - db
    env_file: ../.env
    ports:
      - 3000:8080
  # db:
  #   restart: always
  #   image: postgres:16.0-alpine3.18
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_DB=${DATABASE_DB}
  #   volumes:
  #     - db_volume:/var/lib/postgresql/data
  #   ports:
  #     - 5433:5432

volumes:
  db_volume:

networks:
  nixpig_net:
    driver: bridge
